name: Run testes

on: [push, pull_request]

jobs:
  test:
  run-on: ubuntu-latest

  steps:
  - name: Checkout code 
    uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

      - name: Create .env
      run: echo "database_URL='file:./dev.db'" > .env

      - name :npx prisma gerenate
      run: npx prisma generate

      - name: Load data
      run: npm run load_data

      - name: Run test
      run: npm test